### ISSUE TITLE
ERROR: This operation would block forever

### ISSUE THREAD

**Issue by daemienb** [20c/vaping#102]
Hi Guys,

I'm try to get vaping up & running but i@m getting the below, anyidea

root@serverr:/opt/vaping#fping -u -C10 -p20 -e 8.8.8.8 4.2.2.1 208.67.222.222
8.8.8.8        : 3.36 3.32 3.39 3.35 3.37 3.37 3.36 3.37 3.35 3.43
4.2.2.1        : 9.08 1.93 1.92 1.92 1.89 1.90 1.93 1.90 1.91 1.91
208.67.222.222 : 3.39 3.45 3.51 3.51 3.42 3.51 3.49 3.46 3.45 3.60

root@serverr:/opt/vaping# vaping start --home=/home/user/vaping/examples/standalone_dns/ --debug
pluginmgr hook.compile(vaping.plugins) __init__.py:25
PidFile <pid.posix.PidFile object at 0x7fbd10967340> entering setup base.py:89
PidFile <pid.posix.PidFile object at 0x7fbd10967340> create pidfile: /home/user/vaping/examples/standalone_dns/vaping.pid base.py:194
PidFile <pid.posix.PidFile object at 0x7fbd10967340> check pidfile: /home/user/vaping/examples/standalone_dns/vaping.pid base.py:181
2020-11-11 17:10:30,122 - vaping.plugins.fping - DEBUG: popen fping -u -C10 -p20 -e 8.8.8.8 4.2.2.1 208.67.222.222
vaping.plugins.fping popen fping -u -C10 -p20 -e 8.8.8.8 4.2.2.1 208.67.222.222 __init__.py:112
Exception ignored in: <function _after_fork at 0x7fbd16980e50>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 1486, in _after_fork
    thread._reset_internal_locks(True)
  File "/usr/local/lib/python3.9/threading.py", line 829, in _reset_internal_locks
    self._tstate_lock._at_fork_reinit()
AttributeError: 'NoneType' object has no attribute '_at_fork_reinit'
Exception ignored in: <function _after_at_fork_child_reinit_locks at 0x7fbd16982310>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 251, in _after_at_fork_child_reinit_locks
    handler._at_fork_reinit()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 890, in _at_fork_reinit
    self.lock._at_fork_reinit()
  File "/usr/local/lib/python3.9/threading.py", line 126, in _at_fork_reinit
    self._block._at_fork_reinit()
AttributeError: 'LockType' object has no attribute '_at_fork_reinit'
root 8.8.8.8        : 3.32 3.43 3.49 3.37 3.39 3.46 3.37 3.84 3.38 3.39
 fping.py:85
root 4.2.2.1        : 1.95 1.96 2.17 1.98 1.97 1.94 1.88 1.90 1.95 1.95
 fping.py:85
root 208.67.222.222 : 3.55 3.48 3.44 3.46 3.68 3.47 3.47 3.46 3.60 3.50
 fping.py:85
2020-11-11 17:10:30,865 - vaping.plugins.fping - DEBUG: queue emission to vodka (0)
vaping.plugins.fping queue emission to vodka (0) __init__.py:206
2020-11-11 17:10:33,125 - vaping.plugins.fping - DEBUG: emit to vodka
vaping.plugins.fping emit to vodka __init__.py:203
2020-11-11 17:10:33,191 - vodka - DEBUG: making sure configuration is sane ...
vodka making sure configuration is sane ... log.py:39
2020-11-11 17:10:33,199 - vodka - DEBUG: instantiating data types
vodka instantiating data types log.py:39
2020-11-11 17:10:33,199 - vodka - DEBUG: instantiating plugins
vodka instantiating plugins log.py:39
2020-11-11 17:10:33,202 - vodka - DEBUG: instantiating applications
vodka instantiating applications log.py:39
2020-11-11 17:10:33,202 - vodka - DEBUG: starting plugins
vodka starting plugins log.py:39
2020-11-11 17:10:33,206 - vodka - DEBUG: starting http ..
vodka starting http .. log.py:39
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/usr/local/lib/python3.9/site-packages/vaping/plugins/__init__.py", line 251, in _run
    self.emit_all()
  File "/usr/local/lib/python3.9/site-packages/vaping/plugins/__init__.py", line 227, in emit_all
    self.send_emission()
  File "/usr/local/lib/python3.9/site-packages/vaping/plugins/__init__.py", line 220, in send_emission
    emit()
  File "/usr/local/lib/python3.9/site-packages/vaping/plugins/__init__.py", line 204, in emit
    emitter.emit(msg)
  File "/usr/local/lib/python3.9/site-packages/vaping/plugins/vodka.py", line 99, in emit
    self.start()
  File "/usr/local/lib/python3.9/site-packages/vaping/plugins/vodka.py", line 87, in start
    vodka.run(vodka_config, self.vaping.config)
  File "/usr/local/lib/python3.9/site-packages/vodka/__init__.py", line 148, in run
    start(**init(config, rawConfig))
  File "/usr/local/lib/python3.9/site-packages/vodka/__init__.py", line 116, in start
    t.start()
  File "/usr/local/lib/python3.9/threading.py", line 870, in start
    _start_new_thread(self._bootstrap, ())
  File "/usr/local/lib/python3.9/site-packages/gevent/thread.py", line 81, in start_new_thread
    greenlet = Greenlet.spawn(function, *args)
  File "src/gevent/greenlet.py", line 663, in gevent._greenlet.Greenlet.spawn
AttributeError: type object 'method' has no attribute 'start'
2020-11-11T17:10:33Z <FPing "latency" at 0x7fbd108ff150: _run> failed with AttributeError

2020-11-11 17:10:33,214 - vaping.daemon - ERROR: This operation would block forever
        Hub: <Hub '' at 0x7fbd109511a0 epoll default pending=0 ref=0 fileno=3 thread_ident=0x7fbd18199700>
        Handles:
[]
vaping.daemon This operation would block forever
        Hub: <Hub '' at 0x7fbd109511a0 epoll default pending=0 ref=0 fileno=3 thread_ident=0x7fbd18199700>
        Handles:
[] daemon.py:182
PidFile <pid.posix.PidFile object at 0x7fbd10967340> closing pidfile: /home/user/vaping/examples/standalone_dns/vaping.pid base.py:220
2020-11-11 17:10:33,215 - vaping.daemon - DEBUG: stopping vodka
vaping.daemon stopping vodka daemon.py:222
2020-11-11 17:10:33,216 - vaping.daemon - DEBUG: stopping latency
vaping.daemon stopping latency daemon.py:222
PidFile <pid.posix.PidFile object at 0x7fbd10967340> closing pidfile: /home/user/vaping/examples/standalone_dns/vaping.pid base.py:220
root@serverr:/opt/vaping#

**Comment by vegu** [comment]
Hi @daemienb 

Might be some compatibility issue with python3.9 - do you have access to any older python versions?

We have not had the chance to test and verify that vaping works on python3.9, so at this point that's my best guess.

What's your output of pip freeze?

**Comment by daemienb** [comment]
ah ok cool, what is the recommend version ?

certifi==2020.11.8
chardet==3.0.4
click==7.1.2
docutils==0.16
Flask==1.1.2
future==0.18.2
gevent==1.5.0
graphsrv==1.6.1
greenlet==0.4.16
idna==2.10
itsdangerous==1.1.0
Jinja2==2.11.2
lockfile==0.12.2
MarkupSafe==1.1.1
munge==0.6.0
pid==3.0.4
pluginmgr==0.6.0
python-daemon==2.2.4
PyYAML==5.3.1
requests==2.24.0
subprocess32==3.5.4
twentyc.tmpl==0.2.0
urllib3==1.25.11
vaping==1.3.0
vodka==2.3.0
Werkzeug==1.0.1
whichcraft==0.6.1

**Comment by vegu** [comment]
@daemienb personally i am running it with 3.7, but we have tested 3.6 and 3.8 as well

pip freeze output looks good, so probably fine on that front

**Comment by daemienb** [comment]
ok great will give it go

**Comment by daemienb** [comment]
thanks 3.8 works

**Comment by vegu** [comment]
@daemienb thanks for the confirmation, i have opened an issue for py3.9 support at #103
